# Site settings
title: blackmagic
email: blog@blackmagic.io
description: > # this means to ignore newlines until "baseurl:"
  Stuff I am working on / reading / investigating / very curious about.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.blackmagic.io" # the base hostname & protocol for your site
#github_username:  jfernandezalcon

# Build settings
#markdown: kramdown
markdown: kramdown

defaults:
  values:
    author: "Jose"
